# Generated by Django 5.2.17 on 2026-08-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_verification', '0004_trust_signals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendorcomplaint',
            new_name='vendor_veri_seller__3839e5_idx',
            old_name='vendor_ver_seller__b1a0d7_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorcomplaint',
            new_name='vendor_veri_seller__fe83e1_idx',
            old_name='vendor_ver_seller__c9e7ef_idx',
        ),
    ]
