# Generated by Django 5.2.17 on 2026-08-26 16:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_seed_gateways'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('supported_currencies', models.JSONField(blank=True, default=list)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'provider'],
            },
        ),
    ]
