# Generated by Django 5.2.17 on 2026-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_seed_payout_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutproviderconfig',
            name='supported_countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
