# Generated by Django 5.2.17 on 2026-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=160, null=True, unique=True),
        ),
    ]
