# Generated by Django 5.2.17 on 2026-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgertransaction_idempotency_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('name', 'currency'), name='unique_ledger_account_name_currency'),
        ),
    ]
