# Generated by Django 5.2.17 on 2026-08-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_backgroundjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='adminpanel__status_e5454b_idx',
            old_name='adminpanel_b_status_6d8d7e_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='adminpanel__kind_adef8d_idx',
            old_name='adminpanel_b_kind_7f5b4b_idx',
        ),
    ]
