# Generated by Django 5.2.17 on 2026-08-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsdocument',
            options={'ordering': ['kind', '-created_at']},
        ),
    ]
