# Generated by Django 5.2.17 on 2026-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage4', '0002_alter_termsdocument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsdocument',
            name='kind',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('marketplace', 'Marketplace'), ('escrow', 'Escrow'), ('payments', 'Payments'), ('crypto', 'Crypto'), ('gift_cards', 'Gift Cards'), ('bank_transfer', 'Bank Transfer'), ('withdrawals', 'Withdrawals'), ('disputes', 'Disputes'), ('vendor_verification', 'Vendor Verification'), ('prohibited_items', 'Prohibited Items'), ('privacy', 'Privacy'), ('account_security', 'Account Security')], max_length=20),
        ),
    ]
