# Generated by Django 5.2.17 on 2026-08-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage4', '0006_terms_acceptance_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termsacceptance',
            name='stage4_termsacceptance_unique',
        ),
    ]
