# Generated by Django 5.2.17 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_order_and_message_limits'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_status_5d7ec7_idx',
            old_name='support_tic_status_2f6d59_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_status_d0b46e_idx',
            old_name='support_tic_status_7c9a1a_idx',
        ),
        migrations.AlterField(
            model_name='supportsettings',
            name='agent_response_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Once an agent claims a ticket, the requester has this long to say something. If they go quiet, the ticket expires and the agent is freed up for the next person.'),
        ),
        migrations.AlterField(
            model_name='supportsettings',
            name='max_open_tickets_per_agent',
            field=models.PositiveIntegerField(default=7, help_text="An agent can't be assigned a new ticket while they already have this many open. Adjustable per-agent below as well."),
        ),
    ]
