import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if os.environ.get("DJANGO_DEBUG", "False").lower() == "true":
        SECRET_KEY = "dev-only-change-me"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY must be configured when DEBUG=False.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost"
    ).split(",")
    if host.strip()
]

# Render provides the public service hostname automatically. Add it so a
# production deploy does not fail with Django DisallowedHost. Custom domains
# can be supplied through EXTRA_ALLOWED_HOSTS.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Production security settings.
# Keep these controlled by environment variables so development can still use HTTP.
SECURE_SSL_REDIRECT = os.environ.get(
    "DJANGO_SECURE_SSL_REDIRECT", "False" if DEBUG else "True"
).lower() == "true"

SESSION_COOKIE_SECURE = os.environ.get(
    "DJANGO_SESSION_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() == "true"

CSRF_COOKIE_SECURE = os.environ.get(
    "DJANGO_CSRF_COOKIE_SECURE", "False" if DEBUG else "True"
).lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0")
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "False"
).lower() == "true"

SECURE_HSTS_PRELOAD = os.environ.get(
    "DJANGO_SECURE_HSTS_PRELOAD", "False"
).lower() == "true"



# Application definition

INSTALLED_APPS = [
    'adminpanel.admin_config.ShopUAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'accounts',
    'marketplace',
    'ledger',
    'payments',
    'escrow',
    'telegram_integration',
    'reviews',
    'vendor_verification',
    'audit',
    'adminpanel',
    'finance',
    'giftcards',
    'withdrawals',
    'security',
    'crypto',
    'banktransfer',
    'stage4',
    'referrals',
    'support',
    'controlcenter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if not DATABASE_URL:
    if DEBUG:
        DATABASE_URL = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    else:
        raise RuntimeError(
            "DATABASE_URL must be configured when DEBUG=False."
        )

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")

# User-uploaded media.
#
# Development:
#   local filesystem
#
# Production:
#   Supabase Storage through its S3-compatible API.
if DEBUG:
    MEDIA_ROOT = Path(
        os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media"))
    )
else:
    AWS_ACCESS_KEY_ID = os.environ.get(
        "SUPABASE_S3_ACCESS_KEY_ID", ""
    ).strip()

    AWS_SECRET_ACCESS_KEY = os.environ.get(
        "SUPABASE_S3_SECRET_ACCESS_KEY", ""
    ).strip()

    AWS_S3_ENDPOINT_URL = os.environ.get(
        "SUPABASE_S3_ENDPOINT_URL", ""
    ).strip()

    AWS_S3_REGION_NAME = os.environ.get(
        "SUPABASE_S3_REGION", "us-east-1"
    ).strip()

    AWS_STORAGE_BUCKET_NAME = os.environ.get(
        "SUPABASE_STORAGE_BUCKET", "shopu-media"
    ).strip()

    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Two-bot Telegram architecture:
# - MAIN bot: user-facing marketplace/Mini App bot.
# - NOTIFICATION bot: outbound transactional notifications only.
# Keep the legacy token as a compatibility fallback during migration.
TELEGRAM_MAIN_BOT_TOKEN = os.environ.get(
    "TELEGRAM_MAIN_BOT_TOKEN",
    os.environ.get("TELEGRAM_BOT_TOKEN", ""),
).strip()
TELEGRAM_MAIN_BOT_USERNAME = os.environ.get(
    "TELEGRAM_MAIN_BOT_USERNAME",
    os.environ.get("TELEGRAM_BOT_USERNAME", ""),
).strip().lstrip("@")
TELEGRAM_WEBHOOK_SECRET = os.environ.get(
    "TELEGRAM_WEBHOOK_SECRET",
    "",
).strip()

TELEGRAM_NOTIFICATION_BOT_TOKEN = os.environ.get(
    "TELEGRAM_NOTIFICATION_BOT_TOKEN",
    "",
).strip()

# Backward-compatible names used by older modules.
TELEGRAM_BOT_TOKEN = TELEGRAM_MAIN_BOT_TOKEN
TELEGRAM_BOT_USERNAME = TELEGRAM_MAIN_BOT_USERNAME
TELEGRAM_INIT_DATA_MAX_AGE_SECONDS = int(
    os.environ.get("TELEGRAM_INIT_DATA_MAX_AGE_SECONDS", "3600")
)
TELEGRAM_INIT_DATA_MAX_FUTURE_SECONDS = int(
    os.environ.get("TELEGRAM_INIT_DATA_MAX_FUTURE_SECONDS", "300")
)

PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "").strip()
PAYSTACK_CURRENCY = os.environ.get("PAYSTACK_CURRENCY", "").upper()
PAYSTACK_ALLOWED_CURRENCIES = [
    c.strip().upper() for c in os.environ.get(
        "PAYSTACK_ALLOWED_CURRENCIES", PAYSTACK_CURRENCY
    ).split(",") if c.strip()
]
PAYSTACK_CALLBACK_URL = os.environ.get("PAYSTACK_CALLBACK_URL", "").strip()


# Static files for production / Render
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The Mini App URL can be explicitly configured for a custom domain.
# Otherwise derive it from Render's public hostname. The worker receives
# SHOPU_WEB_HOST from the web service through render.yaml.
MINIAPP_URL = os.environ.get("MINIAPP_URL", "").strip()
if not MINIAPP_URL:
    _miniapp_host = (
        os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
        or os.environ.get("SHOPU_WEB_HOST", "").strip()
    )
    if _miniapp_host:
        MINIAPP_URL = f"https://{_miniapp_host}/miniapp/"
SHOPU_AUTO_RELEASE_HOURS = int(os.environ.get("SHOPU_AUTO_RELEASE_HOURS", "6"))
SHOPU_CRON_SECRET = os.environ.get("SHOPU_CRON_SECRET", "").strip()
SHOPU_GITHUB_ACTIONS_TOKEN = os.environ.get("SHOPU_GITHUB_ACTIONS_TOKEN", "").strip()
SHOPU_GITHUB_REPOSITORY = os.environ.get("SHOPU_GITHUB_REPOSITORY", "").strip()
SHOPU_GITHUB_EVENT_TYPE = os.environ.get("SHOPU_GITHUB_EVENT_TYPE", "shopu-job").strip()
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    _render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_SUCCESS_URL = os.environ.get("STRIPE_SUCCESS_URL", "").strip()
STRIPE_CANCEL_URL = os.environ.get("STRIPE_CANCEL_URL", "").strip()
STRIPE_ALLOWED_CURRENCIES = [
    c.strip().upper() for c in os.environ.get("STRIPE_ALLOWED_CURRENCIES", "").split(",") if c.strip()
]
NOWPAYMENTS_API_KEY = os.environ.get("NOWPAYMENTS_API_KEY", "").strip()
NOWPAYMENTS_IPN_SECRET = os.environ.get("NOWPAYMENTS_IPN_SECRET", "").strip()
NOWPAYMENTS_BASE_URL = os.environ.get("NOWPAYMENTS_BASE_URL", "https://api.nowpayments.io/v1").rstrip("/")
NOWPAYMENTS_IPN_URL = os.environ.get("NOWPAYMENTS_IPN_URL", "").strip()

# Use short-lived database connections during local test runs.
if os.environ.get("DJANGO_TESTING", "").lower() == "true":
    DATABASES["default"]["CONN_MAX_AGE"] = 0


# ShopU payout providers
STRIPE_CONNECT_PAYOUT_ENABLED = os.environ.get(
    "STRIPE_CONNECT_PAYOUT_ENABLED", "0"
) == "1"

AIRWALLEX_PAYOUT_ENABLED = os.environ.get(
    "AIRWALLEX_PAYOUT_ENABLED", "0"
) == "1"
AIRWALLEX_CLIENT_ID = os.environ.get(
    "AIRWALLEX_CLIENT_ID", ""
).strip()
AIRWALLEX_API_KEY = os.environ.get(
    "AIRWALLEX_API_KEY", ""
).strip()
AIRWALLEX_BASE_URL = os.environ.get(
    "AIRWALLEX_BASE_URL",
    "https://api.airwallex.com",
).rstrip("/")

MANGOPAY_PAYOUT_ENABLED = os.environ.get(
    "MANGOPAY_PAYOUT_ENABLED", "0"
) == "1"
MANGOPAY_CLIENT_ID = os.environ.get(
    "MANGOPAY_CLIENT_ID", ""
).strip()
MANGOPAY_API_KEY = os.environ.get(
    "MANGOPAY_API_KEY", ""
).strip()
MANGOPAY_BASE_URL = os.environ.get(
    "MANGOPAY_BASE_URL",
    "https://api.mangopay.com",
).rstrip("/")

NOWPAYMENTS_PAYOUT_ENABLED = os.environ.get(
    "NOWPAYMENTS_PAYOUT_ENABLED", "0"
) == "1"



# Use Django Admin authentication for the ShopU Control Center.
LOGIN_URL = "/admin/login/"
