# Generated by Django 5.2.17 on 2026-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='provider',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe', 'Stripe Connect')], max_length=40),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='provider_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(default='bank', max_length=40),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
