# Generated by Django 5.2.17 on 2026-08-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_alter_withdrawalrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='provider',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe_connect', 'Stripe Connect'), ('airwallex', 'Airwallex'), ('mangopay', 'Mangopay'), ('nowpayments', 'NOWPayments')], max_length=40),
        ),
    ]
