# Generated by Django 5.2.17 on 2026-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_escrow_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateescrow',
            name='funded_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='privateescrow',
            name='funded_gift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='privateescrow',
            name='funding_transaction_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
