# Generated by Django 5.2.17 on 2026-08-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_privateescrow_funded_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrow',
            options={'permissions': [('settle_escrow', 'Can settle escrow')]},
        ),
    ]
